Sanketika-Obsrv/obsrv-automation

terraform/helm/monitoring.tf, terraform/helm/monitoring_vars.tf, terraform/terraform_helm_templates/monitoring.yaml.tfpl
=> fix: adding PV for prom

terraform/aws/main.tf, terraform/aws/variables.tf, terraform/modules/helm/dataset_api/dataset_api.yaml.tfpl, terraform/modules/helm/flink/flink-helm-chart-sa/Chart.yaml, terraform/modules/helm/flink/flink-helm-chart-sa/templates/_helpers.tpl, terraform/modules/helm/flink/flink-helm-chart-sa/templates/serviceaccount.yaml, terraform/modules/helm/flink/flink-helm-chart-sa/values.yaml, terraform/modules/helm/flink/flink.yaml.tfpl, terraform/modules/helm/flink/flink.yaml.tfpl-sa, terraform/modules/helm/flink/main.tf, terraform/modules/helm/flink/variables.tf, terraform/modules/helm/kafka/kafka.yaml.tfpl, terraform/modules/helm/kafka/main.tf, terraform/modules/helm/kafka/variables.tf, terraform/modules/helm/secor/main.tf, terraform/modules/helm/secor/secor.yaml.tfpl, terraform/modules/helm/secor/variables.tf
- Deploying flink service account
- Refactor terraform variables for flink
- Fix storage class for secor
- Modify secor template file
- Fix missing variables in secor terraform file.
- Add a kafka topic
- Fix typo in dataset api tfpl file.
=> Deploy flink service account and secor fixes

terraform/aws/main.tf, terraform/aws/variables.tf, terraform/modules/helm/flink/flink-helm-chart/templates/flink_job_deployment.yaml, terraform/modules/helm/flink/flink.yaml.tfpl, terraform/modules/helm/flink/main.tf, terraform/modules/helm/flink/variables.tf
-  Flink deployment terraform changes for multiple releases
=> Flink release deploy

INSTALLATION.md
Refactor the definitions and explanations in the document.
=> Issue #0 fix: refactor installation guide.

terraform/modules/helm/dataset_api/dataset-api-helm-chart/values.yaml, terraform/modules/helm/druid_exporter/druid-exporter-helm-chart/values.yaml, terraform/modules/helm/druid_raw_cluster/druid-raw-cluster-helm-chart/values.yaml, terraform/modules/helm/flink/flink-helm-chart-sa/values.yaml, terraform/modules/helm/flink/flink-helm-chart/values.yaml, terraform/modules/helm/kafka/kafka-helm-chart/values.yaml, terraform/modules/helm/kafka_exporter/kafka-exporter-helm-chart/values.yaml, terraform/modules/helm/postgresql/postgresql-helm-chart/values.yaml, terraform/modules/helm/postgresql_exporter/postgresql-exporter-helm-chart/values.yaml, terraform/modules/helm/redis/values.yaml, terraform/modules/helm/secor/secor-helm-chart-sa/values.yaml, terraform/modules/helm/secor/secor-helm-chart/values.yaml, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/values.yaml, terraform/modules/helm/superset/superset-helm-chart/values.yaml, terraform/modules/helm/web_console/web-console-helm-chart/values.yaml
- PR for refactoring helm values file for all the services
=> feat: update helm values for all the services

terraform/aws/main.tf, terraform/azure/main.tf, terraform/gcp/main.tf, terraform/modules/helm/command_service/command-service-helm-chart/templates/command_api_deployment.yml, terraform/modules/helm/command_service/command-service.yaml.tfpl, terraform/modules/helm/command_service/main.tf, terraform/modules/helm/command_service/variables.tf
This PR includes:
* removing docker secret variables from the terraform files from the command service module, since open source version uses public images.
=> Removal of docker secrets

terraform/modules/helm/dataset_api/dataset-api-helm-chart/templates/deployment.yaml
fixed the dataset-api deployment  indentation issue
=> dataset-api deployment  indentation issue fix

terraform/aws/variables.tf, terraform/azure/variables.tf, terraform/gcp/variables.tf, terraform/modules/helm/flink/variables.tf
This PR includes:
updated image tags for the following images for release 1.1.0
* flink
=> Updated image tags according to release 1.1.0

terraform/modules/helm/postgresql_migration/postgresql-migration-helm-chart/migration/03_obsrv/V1__create_obsrv_initial_data.sql
Changes made -
- Add default value as current timestamp in the postgres tables for `published_date` columns
=> #90 fix: Postgres schema update

terraform/aws/main.tf, terraform/aws/variables.tf, terraform/modules/aws/eks/variables.tf, terraform/modules/aws/get_kubeconfig/main.tf, terraform/modules/aws/get_kubeconfig/variables.tf, terraform/modules/aws/vpc/variables.tf, terraform/modules/helm/dataset_api/dataset-api-helm-chart/values.yaml, terraform/modules/helm/secor/secor-helm-chart/values.yaml, terraform/modules/helm/secor/variables.tf, terraform/modules/helm/velero/values.yaml
This pull request removes the default region values that were previously set in the script.
The default region values were initially set to "us-east-2". However, after  discussions, it was decided to remove these default values.
Developers using this should be aware that they now need to explicitly specify the region values.
The changes have been tested in dev cluster to ensure that the infra provisioning behaves as expected after removing the default region values.
Closes  #196
=> #196 Fix:Remove default region.

terraform/modules/helm/postgresql_migration/postgresql-migration-helm-chart/migration/03_obsrv/V1__create_obsrv_initial_data.sql
Changes made -
- Add new column for datasources table
=> #126 feat: add new property to datasources table

terraform/modules/azure/aks/variables.tf
This pr contains - 
- Make node count to 5 
- Update node instance type (4C 16G)
=> update node count and instance size for azure

terraform/aws/variables.tf
This PR consists of new image tags
=> feat new image tags

terraform/modules/helm/secor/secor-helm-chart/values.yaml, terraform/modules/helm/secor/secor.yaml.tfpl, terraform/modules/helm/secor/variables.tf, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/templates/configmap.yaml, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/templates/deployment.yaml, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/values.yaml, terraform/modules/helm/submit_ingestion/submit_ingestion.yaml.tfpl
The PR include the automated submission of druid ingestion spec for system telemetry events and configuration a Secor backup to backup the system telemetry events.
=> System Telemetry Events Ingestion Spec and Backup Configurations

terraform/aws/main.tf, terraform/aws/variables.tf, terraform/modules/helm/postgresql_migration/main.tf, terraform/modules/helm/postgresql_migration/postgresql-migration-helm-chart/migration/03_obsrv/V2__create_system_settings.sql, terraform/modules/helm/postgresql_migration/postgresql-migration-helm-chart/values.yaml, terraform/modules/helm/postgresql_migration/postgresql_migration.yaml.tfpl, terraform/modules/helm/postgresql_migration/variables.tf, terraform/modules/helm/secor/main.tf, terraform/modules/helm/secor/secor-helm-chart/templates/secor-statefulset.yaml, terraform/modules/helm/secor/secor-helm-chart/values.yaml, terraform/modules/helm/secor/secor.yaml.tfpl, terraform/modules/helm/secor/variables.tf, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/templates/configmap.yaml, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/templates/deployment.yaml, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/values.yaml, terraform/modules/helm/submit_ingestion/submit_ingestion.yaml.tfpl, terraform/modules/helm/superset/superset-helm-chart/templates/configmap-dashboards.yaml, terraform/modules/helm/superset/superset-helm-chart/templates/deployment.yaml, terraform/modules/helm/superset/superset-helm-chart/templates/init-job.yaml, terraform/modules/helm/superset/superset-helm-chart/values.yaml
* Fix: removed docker secrets
* updated the grafana_secrete
* Feat: updated image tags according to release 1.1.0
* Issue #171 feat: update job to deployment for jobmanagers
* #90 fix: Add default value for published_date in tables (#94)
* fix: remove restart policy from flink deployment manifest (#96)
* #196 Fix:Remove default region. (#95)
* fix: #196 remove default value for region
* update: #196 missing variable in variables.tf file
* #196 update:  example on how provide region
* #196 update: comments on how to provide region
* Separation of redis into dedup & meta/denorm. (#92)
* feat: Separation of redis into dedup & meta/denorm.
* feat: Separation of redis into dedup & meta/denorm.
* feat: Separation of redis into dedup & meta/denorm.
* feat: Separation of redis into dedup & …
=> Release-1.0.0-GA to Main

terraform/aws/main.tf, terraform/aws/variables.tf, terraform/modules/helm/postgresql_migration/main.tf, terraform/modules/helm/postgresql_migration/postgresql-migration-helm-chart/migration/03_obsrv/V2__create_system_settings.sql, terraform/modules/helm/postgresql_migration/postgresql-migration-helm-chart/values.yaml, terraform/modules/helm/postgresql_migration/postgresql_migration.yaml.tfpl, terraform/modules/helm/postgresql_migration/variables.tf, terraform/modules/helm/secor/main.tf, terraform/modules/helm/secor/secor-helm-chart/templates/secor-statefulset.yaml, terraform/modules/helm/secor/secor-helm-chart/values.yaml, terraform/modules/helm/secor/secor.yaml.tfpl, terraform/modules/helm/secor/variables.tf, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/templates/configmap.yaml, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/templates/deployment.yaml, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/values.yaml, terraform/modules/helm/submit_ingestion/submit_ingestion.yaml.tfpl, terraform/modules/helm/superset/superset-helm-chart/templates/configmap-dashboards.yaml, terraform/modules/helm/superset/superset-helm-chart/templates/deployment.yaml, terraform/modules/helm/superset/superset-helm-chart/templates/init-job.yaml, terraform/modules/helm/superset/superset-helm-chart/values.yaml
* Fix: removed docker secrets
* updated the grafana_secrete
* Feat: updated image tags according to release 1.1.0
* Issue #171 feat: update job to deployment for jobmanagers
* #90 fix: Add default value for published_date in tables (#94)
* fix: remove restart policy from flink deployment manifest (#96)
* #196 Fix:Remove default region. (#95)
* fix: #196 remove default value for region
* update: #196 missing variable in variables.tf file
* #196 update:  example on how provide region
* #196 update: comments on how to provide region
* Separation of redis into dedup & meta/denorm. (#92)
* feat: Separation of redis into dedup & meta/denorm.
* feat: Separation of redis into dedup & meta/denorm.
* feat: Separation of redis into dedup & meta/denorm.
* feat: Separation of redis into dedup & …
=> Rebase Develop with release-1.0.0-GA 

terraform/aws/main.tf, terraform/aws/variables.tf, terraform/modules/helm/postgresql_migration/main.tf, terraform/modules/helm/postgresql_migration/postgresql-migration-helm-chart/migration/03_obsrv/V2__create_system_settings.sql, terraform/modules/helm/postgresql_migration/postgresql-migration-helm-chart/values.yaml, terraform/modules/helm/postgresql_migration/postgresql_migration.yaml.tfpl, terraform/modules/helm/postgresql_migration/variables.tf, terraform/modules/helm/secor/main.tf, terraform/modules/helm/secor/secor-helm-chart/templates/secor-statefulset.yaml, terraform/modules/helm/secor/secor-helm-chart/values.yaml, terraform/modules/helm/secor/secor.yaml.tfpl, terraform/modules/helm/secor/variables.tf, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/templates/configmap.yaml, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/templates/deployment.yaml, terraform/modules/helm/submit_ingestion/submit-ingestion-helm-chart/values.yaml, terraform/modules/helm/submit_ingestion/submit_ingestion.yaml.tfpl, terraform/modules/helm/superset/superset-helm-chart/templates/configmap-dashboards.yaml, terraform/modules/helm/superset/superset-helm-chart/templates/deployment.yaml, terraform/modules/helm/superset/superset-helm-chart/templates/init-job.yaml, terraform/modules/helm/superset/superset-helm-chart/values.yaml
* Fix: removed docker secrets
* updated the grafana_secrete
* Feat: updated image tags according to release 1.1.0
* Issue #171 feat: update job to deployment for jobmanagers
* #90 fix: Add default value for published_date in tables (#94)
* fix: remove restart policy from flink deployment manifest (#96)
* #196 Fix:Remove default region. (#95)
* fix: #196 remove default value for region
* update: #196 missing variable in variables.tf file
* #196 update:  example on how provide region
* #196 update: comments on how to provide region
* Separation of redis into dedup & meta/denorm. (#92)
* feat: Separation of redis into dedup & meta/denorm.
* feat: Separation of redis into dedup & meta/denorm.
* feat: Separation of redis into dedup & meta/denorm.
* feat: Separation of redis into dedup & …
=> Merge release-1.0.0-GA (#124) (#125) to open source branch

terraform/modules/helm/kafka/outputs.tf
Changes made -
- Add kafka module output variables
=> #172 Feat: Add outputs for kafka module

automation-scripts/infra-setup/setup.conf, automation-scripts/infra-setup/setup.sh, terraform/aws/main.tf, terraform/aws/variables.tf, terraform/modules/aws/eks/variables.tf, terraform/modules/helm/flink/flink-helm-chart/values.yaml, terraform/modules/helm/monitoring/main.tf, terraform/modules/helm/monitoring/monitoring.yaml.tfpl, terraform/modules/helm/monitoring/variables.tf
This PR includes -
- Installation fixes
- Enabling kafka-connector job
- Upgrading EKS version
=> Installation fixes

terraform/azure/main.tf, terraform/azure/variables.tf, terraform/modules/helm/unified_helm/main.tf, terraform/modules/helm/unified_helm/variables.tf
This pr contains - Terraform changes to deploy open source version for azure using umbrella chart
=> Azure terraform changes

terraform/modules/aws/eks/main.tf
This pr contains - Terraform changes to deletes cloudwatch log group
=> terraform destroy deletes cloudwatch log group

terraform/modules/helm/superset/superset-helm-chart/values.yaml, terraform/modules/helm/superset/variables.tf
Corrected the redis ip address in the superset helm chart
=> Correct the redis ip address in the superset helm chart

helmcharts/services/postgresql-migration/configs/migrations/03-obsrv/V6__dataset_alias.sql
**Description:**
Added a new column "alias" as dataset alias name for Datasets table
=> fix: #OBS-I452 Column alias in datasets table

helmcharts/services/dataset-api/values.yaml
Added obsrv version variable in env
=> feat: #OBS-I597: adding env variable for specifying obsrv version

helmcharts/services/dataset-api/configs/alertsConfig.json, helmcharts/services/system-rules-ingestor/configs/rules.yaml
Changed the interval format from hours to minutes as web console just supports view and edit of interval in minutes
=> feat #OBS-I623 : alert frequency changes to minutes

helmcharts/global-values.yaml
Added env variable for telemetry log
=> feat: #ITD-I25: added env variable for telemtery_log

connectors/register.sh, helmcharts/kitchen/install.sh
Once all the services are deployed , we can automatically register the all the available connectors by default.
=> Register all the available connectors by default

Dockerfiles/flink-connectors/Dockerfile, Dockerfiles/flink/Dockerfile, connectors/register.sh, helmcharts/bootstrapper/templates/secrets.yaml, helmcharts/global-values.yaml, helmcharts/images.yaml, helmcharts/kitchen/install.sh, helmcharts/services/command-api/configs/service_config.yml, helmcharts/services/command-api/values.yaml, helmcharts/services/dataset-api/values.yaml, helmcharts/services/druid-exporter/templates/deployment.yaml, helmcharts/services/druid-raw-cluster/values.yaml, helmcharts/services/flink/values.yaml, helmcharts/services/hms/values.yaml, helmcharts/services/kube-prometheus-stack/templates/_helpers.tpl, helmcharts/services/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml, helmcharts/services/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/deployment.yaml, helmcharts/services/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml, helmcharts/services/kube-prometheus-stack/templates/prometheus/prometheus.yaml, helmcharts/services/lakehouse-connector/templates/deployment.yaml, helmcharts/services/lakehouse-connector/values.yaml, helmcharts/services/postgresql-migration/templates/job.yaml, helmcharts/services/submit-ingestion/templates/job.yaml, helmcharts/services/submit-ingestion/values.yaml, helmcharts/services/velero/templates/deployment.yaml, helmcharts/services/volume-autoscaler/values.yaml
Merge release branch "Release 1.10.0" into "main"
=> Release 1.10.0

helmcharts/services/command-api/configs/connectors-scala-config.conf, helmcharts/services/flink/values.yaml
1. Updated the checkpointing interval for flink-connector to 5 seconds
=> updated checkpointing inteval for flink-connector
